### ISSUE TITLE
Friday Demo To-Do List

### ISSUE THREAD

**Issue by sahilshahpatel** [frilel/Tomtar-2022#5]
Need to have:
- [x] Implement basic puzzles {Sahil}
- [x] Add basic colliders and deadzones to environment (focus on the kitchen for now) {Olaf}

Nice to have:
- [x] Fix P2 initial spawn point
- [x] Redo checkpoint materials so that both can show at once
- [ ] Prevent jumping up slopes (https://forum.unity.com/threads/how-to-avoid-jumping-up-steep-terrain.15500/)
- [x] Players should move along with moving platforms (friction)

**Comment by frilel** [comment]
Been looking into the jump/sliding on slopes.

Sliding down on un-walkable slopes seems too hard to fix with the in-built character controller. We would have to make our own character controller to implement more physics behavior I think. I personally don't want to work on that on this course >_<

Continuously jumping on slopes seems to be fixed with lowering the "slope limit" variable on the character controller however:
![image](https://user-images.githubusercontent.com/59727728/162283329-053dc750-2ae6-41b0-8378-ff5f163b8dd8.png)
